version: "3.7"

services:

# docker run -dp 3000:3000 \
# --network todo-app \
# -e MYSQL_HOST=mysql \
# -e MYSQL_USER=root \
# -e MYSQL_PASSWORD=secret \
# -e MYSQL_DB=todos \
# urielch19/my_app:v2

  app:
    image: urielch19/my_app:v2
    ports: 
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret
      MYSQL_DB: todos
  
# docker run -d \
# --network todo-app --network-alias mysql \
# -v /Users/joan_amengual/Desktop/multi-container/todo-mysql-data:/var/lib/mysql \ 
# -e MYSQL_ROOT_PASSWORD=secret \
# -e MYSQL_DATABASE=todos \
# mysql:5.7

  mysql:
    image: mysql:5.7
    volumes:
    - /home/uriel/Documents/multi-container/todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: todos


